<a href="https://colab.research.google.com/github/vataliya/cav_security_attacls/blob/main/cav_sec_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
cd drive/My\ Drive/Colab\ Notebooks/kdd99/NSL-KDD

/content/drive/My Drive/Colab Notebooks/kdd99/NSL-KDD


In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

**Data Import and Preprocessing**

In [4]:
columns = ['duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_files',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'labels'
]

cav_attacks_list = [
    'ipsweep',
    'imap',
    'mailbomb', 
    'neptune', 
    'pod', 
    'smurf', 
    'teardrop', 
    'udpstorm',
    'buffer_overflow', 
    'httptunnel',
    'ftp_write', 
    'guess_passwd', 
    'worm', 
    'xsnoop',
    'normal']

In [5]:
nsl_kdd_20p_train = pd.read_csv('KDDTrain+.txt', names = columns, index_col=False)
cav_train = nsl_kdd_20p_train[nsl_kdd_20p_train['labels'].isin(cav_attacks_list)]

In [6]:
nsl_kdd_20p_test = pd.read_csv('KDDTest+.txt', names = columns, index_col=False)
cav_test = nsl_kdd_20p_test[nsl_kdd_20p_test['labels'].isin(cav_attacks_list)]

In [7]:
attacks = np.concatenate((nsl_kdd_20p_train['labels'].unique(),nsl_kdd_20p_test['labels'].unique()))
attacks = np.unique(attacks)

In [8]:
nsl_kdd_20p_train_list = nsl_kdd_20p_train['labels'].value_counts()
cav_train_list = cav_train['labels'].value_counts()
nsl_kdd_20p_test_list = nsl_kdd_20p_test['labels'].value_counts()
cav_test_list = cav_test['labels'].value_counts()

In [9]:
dataset_values = pd.DataFrame(index = attacks, columns = ['NSL_KDD_Train', 'NSL_KDD_Test', 'CAV_Train', 'CAV_Test'])
dataset_values['NSL_KDD_Train'] = nsl_kdd_20p_train_list
dataset_values['NSL_KDD_Test'] = nsl_kdd_20p_test_list
dataset_values['CAV_Train'] = cav_train_list
dataset_values['CAV_Test'] = cav_test_list
dataset_values.sort_values(by=['NSL_KDD_Train'], ascending = False)

NSL_KDD_Train  NSL_KDD_Test  CAV_Train  CAV_Test
normal                 67343.0        9711.0    67343.0    9711.0
neptune                41214.0        4657.0    41214.0    4657.0
satan                   3633.0         735.0        NaN       NaN
ipsweep                 3599.0         141.0     3599.0     141.0
portsweep               2931.0         157.0        NaN       NaN
smurf                   2646.0         665.0     2646.0     665.0
nmap                    1493.0          73.0        NaN       NaN
back                     956.0         359.0        NaN       NaN
teardrop                 892.0          12.0      892.0      12.0
warezclient              890.0           NaN        NaN       NaN
pod                      201.0          41.0      201.0      41.0
guess_passwd              53.0        1231.0       53.0    1231.0
buffer_overflow           30.0          20.0       30.0      20.0
warezmaster               20.0         944.0        NaN       NaN
land                      18.0           7.0        NaN       NaN
imap                      11.0           1.0       11.0       1.0
rootkit                   10.0          13.0        NaN       NaN
loadmodule                 9.0           2.0        NaN       NaN
ftp_write                  8.0           3.0        8.0       3.0
multihop                   7.0          18.0        NaN       NaN
phf                        4.0           2.0        NaN       NaN
perl                       3.0           2.0        NaN       NaN
spy                        2.0           NaN        NaN       NaN
apache2                    NaN         737.0        NaN       NaN
httptunnel                 NaN         133.0        NaN     133.0
mailbomb                   NaN         293.0        NaN     293.0
mscan                      NaN         996.0        NaN       NaN
named                      NaN          17.0        NaN       NaN
processtable               NaN         685.0        NaN       NaN
ps                         NaN          15.0        NaN       NaN
saint                      NaN         319.0        NaN       NaN
sendmail                   NaN          14.0        NaN       NaN
snmpgetattack              NaN         178.0        NaN       NaN
snmpguess                  NaN         331.0        NaN       NaN
sqlattack                  NaN           2.0        NaN       NaN
udpstorm                   NaN           2.0        NaN       2.0
worm                       NaN           2.0        NaN       2.0
xlock                      NaN           9.0        NaN       NaN
xsnoop                     NaN           4.0        NaN       4.0
xterm                      NaN          13.0        NaN       NaN

In [10]:
cav_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115997 entries, 0 to 125972
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   duration                     115997 non-null  int64  
 1   protocol_type                115997 non-null  object 
 2   service                      115997 non-null  object 
 3   flag                         115997 non-null  object 
 4   src_bytes                    115997 non-null  int64  
 5   dst_bytes                    115997 non-null  int64  
 6   land                         115997 non-null  int64  
 7   wrong_fragment               115997 non-null  int64  
 8   urgent                       115997 non-null  int64  
 9   hot                          115997 non-null  int64  
 10  num_failed_logins            115997 non-null  int64  
 11  logged_in                    115997 non-null  int64  
 12  num_compromised              115997 non-null  int64  
 13 

In [11]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
for i in columns:
    cav_train[i] = le.fit_transform(cav_train[i])
    cav_test[i] = le.fit_transform(cav_test[i])

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
x_train = cav_train.drop(columns= ['labels'])
y_train = cav_train['labels']
x_test = cav_test.drop(columns= ['labels'])
y_test = cav_test['labels']

In [14]:
#scaling the data
sc=StandardScaler()
x_sc = sc.fit_transform(x_train)
xt_sc=sc.transform(x_test)

In [15]:
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras import layers, models

In [16]:
train_dataset = cav_train.values
X_train = train_dataset[:,:40]
y_train = train_dataset[:,41]

test_dataset = cav_test.values
X_test = test_dataset[:,:40]
y_test = test_dataset[:,41]

In [17]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical

# one hot encode
encoded_ytrain = to_categorical(y_train)
encoded_ytest = to_categorical(y_test)

print(encoded_ytrain)
print(encoded_ytest)
# invert encoding
inverted = argmax(encoded_ytrain[0])
print(inverted)

y_inverted = []
for i in encoded_ytest:
  y_inverted.append(argmax(i))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
6


In [18]:
# mlp for multi-label classification
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# get the model
def get_model(n_inputs, n_outputs):
  model = Sequential()
  model.add(Dense(80, input_dim=n_inputs, activation='relu'))
  model.add(Dense(160, activation='relu'))
  model.add(Dense(80, activation='relu'))
  model.add(Dense(n_outputs, activation='sigmoid'))
  model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
  return model

# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y, X_test, y_test):
  n_inputs, n_outputs = X.shape[1], y.shape[1]
  X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
  # define model
  model = get_model(n_inputs, n_outputs)
  model.summary()
  # fit model
  model.fit(X_train, y_train, verbose=1, epochs=10, validation_data = (X_val, y_val))
  # make a prediction on the test set
  yhat = model.predict(X_test)
  inverted = []
  for i in yhat:
    inverted.append(argmax(i))  
  inverted = np.array(inverted)
  print(inverted)
  # # calculate accuracy
  report = classification_report(y_test, inverted)
  print(report)
  return report


In [19]:
# evaluate model
results = evaluate_model(x_train, encoded_ytrain, x_test, y_inverted)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 80)                3360      
_________________________________________________________________
dense_1 (Dense)              (None, 160)               12960     
_________________________________________________________________
dense_2 (Dense)              (None, 80)                12880     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                810       
Total params: 30,010
Trainable params: 30,010
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
2900/2900 [==============================] - 7s 2ms/step - loss: 0.4554 - accuracy: 0.9567 - val_loss: 0.4374 - val_accuracy: 0.9632
Epoch 2/10
2900/2900 [==============================] - 7s 2ms/step - loss: 0.4434 - accuracy: 0.9629 - va